/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;
import control.EmprestimoControl;
import entity.EmprestimoBean;
import javax.swing.JOptionPane;
/**
 *
 * @author paulo
 */
public class ManterEmprestimo extends javax.swing.JFrame {
    
    //EmprestimoControl mec = new EmprestimoControl();
    //EmprestimoBean entity = new EmprestimoBean();
    
    
    public void cadastrarEmprestimo(){ //Deveria estar no pacote Control
        
        EmprestimoBean emprestimo = new EmprestimoBean();
        emprestimo.setCodigoObra(Integer.parseInt(tfCodigoEmp.getText().trim()));
        emprestimo.setTituloObra(tfTituloEmp.getText().trim());
        emprestimo.setAutorObra(tfAutorEmp.getText().trim());
        emprestimo.setTipoOperacao(cbTipoOperacaoEmp.getSelectedItem().toString());
        emprestimo.setMuseuObra(cbMuseuEmp.getSelectedItem().toString());
        //emprestimo.setDataDia(Integer.parseInt(cbDiaEmp.getSelectedItem().toString()));
        //emprestimo.setDataMes(cbMesEmp.getSelectedItem().toString());
        //emprestimo.setDataAno(Integer.parseInt(cbAnoEmp.getSelectedItem().toString()));
        emprestimo.setDataOperacaoEmp(ftfDataOperacaoEmp.getText());
        emprestimo.setTransporteEmp(tfEmpresaTranspEmp.getText().trim());
        emprestimo.setTransporteTipo(cbTipoTransporteEmpr.getSelectedItem().toString());
        emprestimo.setTransportePreco(Double.parseDouble(tfPrecoTransporteEmp.getText().trim()));
        emprestimo.setTransportePagador(cbPagadorTransporteEmp.getSelectedItem().toString());
        EmprestimoControl c = new EmprestimoControl();
        c.cadastraEmprestimo(emprestimo);
    
        
    
    
    }
    
    
    /**
     * Creates new form Manter_emprestimo_Boundary
     */
    public ManterEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Codigo_Label = new javax.swing.JLabel();
        Titulo_Label = new javax.swing.JLabel();
        Autor_Label = new javax.swing.JLabel();
        Tipo_de_Operacao = new javax.swing.JLabel();
        Museu_Label = new javax.swing.JLabel();
        Data_Operacao_Label = new javax.swing.JLabel();
        Transporte_Label = new javax.swing.JLabel();
        Empresa_Label = new javax.swing.JLabel();
        Tipo_Transporte_Label = new javax.swing.JLabel();
        Preco_Label = new javax.swing.JLabel();
        Pagador_Label = new javax.swing.JLabel();
        Voltar_botao = new javax.swing.JButton();
        Cadastrar_botao = new javax.swing.JButton();
        tfCodigoEmp = new javax.swing.JTextField();
        tfTituloEmp = new javax.swing.JTextField();
        tfAutorEmp = new javax.swing.JTextField();
        tfEmpresaTranspEmp = new javax.swing.JTextField();
        cbTipoTransporteEmpr = new javax.swing.JComboBox();
        tfPrecoTransporteEmp = new javax.swing.JTextField();
        cbPagadorTransporteEmp = new javax.swing.JComboBox();
        cbTipoOperacaoEmp = new javax.swing.JComboBox();
        cbMuseuEmp = new javax.swing.JComboBox();
        Busca_Titulo_Botao = new javax.swing.JButton();
        Busca_Autor_Botao = new javax.swing.JButton();
        ftfDataOperacaoEmp = new javax.swing.JFormattedTextField();

        setTitle("Controle de Empréstimo");
        setResizable(false);

        Codigo_Label.setText("Código:");

        Titulo_Label.setText("Título:");

        Autor_Label.setText("Autor:");

        Tipo_de_Operacao.setText("Tipo de Operação:");

        Museu_Label.setText("Museu:");

        Data_Operacao_Label.setText("Data da operação:");

        Transporte_Label.setText("Transporte");

        Empresa_Label.setText("Empresa:");

        Tipo_Transporte_Label.setText("Tipo de transporte:");

        Preco_Label.setText("Preço:");

        Pagador_Label.setText("Pagador:");

        Voltar_botao.setText("Voltar");

        Cadastrar_botao.setText("Cadastrar");
        Cadastrar_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_botaoActionPerformed(evt);
            }
        });

        tfCodigoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoEmpActionPerformed(evt);
            }
        });

        tfTituloEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTituloEmpActionPerformed(evt);
            }
        });

        cbTipoTransporteEmpr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aéreo", "Marítimo", "Terrestre" }));

        cbPagadorTransporteEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fulano 1", "Fulano 2", "Fulano 3", "Fulano 4", "Fulano 5", "Fulano 6", "Fulano 7", "Fulano 8", "Fulano 9", "Fulano 10" }));

        cbTipoOperacaoEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operação 1", "Operação 2", "Operação 3", "Operação 4", "Operação 5", "Operação 6", "Operação 7", "Operação 8", "Operação 9", "Operação 10" }));

        cbMuseuEmp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Museu 1", "Museu 2", "Museu 3", "Museu 4", "Museu 5", "Museu 6", "Museu 7", "Museu 8", "Museu 9", "Museu 10" }));
        cbMuseuEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMuseuEmpActionPerformed(evt);
            }
        });

        Busca_Titulo_Botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busca_Titulo_BotaoActionPerformed(evt);
            }
        });

        try {
            ftfDataOperacaoEmp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Data_Operacao_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftfDataOperacaoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Voltar_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Cadastrar_botao))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Empresa_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfEmpresaTranspEmp))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Tipo_Transporte_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbTipoTransporteEmpr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Preco_Label)
                            .addGap(6, 6, 6)
                            .addComponent(tfPrecoTransporteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Pagador_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbPagadorTransporteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Transporte_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Tipo_de_Operacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbTipoOperacaoEmp, 0, 194, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(Museu_Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbMuseuEmp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Codigo_Label)
                            .addComponent(Titulo_Label)
                            .addComponent(Autor_Label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCodigoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTituloEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tfAutorEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Busca_Autor_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Busca_Titulo_Botao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo_Label)
                    .addComponent(tfCodigoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Busca_Titulo_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titulo_Label)
                        .addComponent(tfTituloEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Busca_Autor_Botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Autor_Label)
                        .addComponent(tfAutorEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo_de_Operacao)
                    .addComponent(cbTipoOperacaoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Museu_Label)
                    .addComponent(cbMuseuEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Data_Operacao_Label)
                    .addComponent(ftfDataOperacaoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Transporte_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empresa_Label)
                    .addComponent(tfEmpresaTranspEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo_Transporte_Label)
                    .addComponent(cbTipoTransporteEmpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preco_Label)
                    .addComponent(tfPrecoTransporteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pagador_Label)
                    .addComponent(cbPagadorTransporteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar_botao)
                    .addComponent(Cadastrar_botao))
                .addContainerGap())
        );

        Busca_Titulo_Botao.getAccessibleContext().setAccessibleName("Busca_Titulo_Botao");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoEmpActionPerformed

    private void Busca_Titulo_BotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busca_Titulo_BotaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busca_Titulo_BotaoActionPerformed

    
    
    
    private void Cadastrar_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_botaoActionPerformed
       cadastrarEmprestimo();
       //mec.limpaTela();
       
    }//GEN-LAST:event_Cadastrar_botaoActionPerformed

    
    
 
    private void tfTituloEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTituloEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTituloEmpActionPerformed

    private void cbMuseuEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMuseuEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMuseuEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor_Label;
    private javax.swing.JButton Busca_Autor_Botao;
    private javax.swing.JButton Busca_Titulo_Botao;
    private javax.swing.JButton Cadastrar_botao;
    private javax.swing.JLabel Codigo_Label;
    private javax.swing.JLabel Data_Operacao_Label;
    private javax.swing.JLabel Empresa_Label;
    private javax.swing.JLabel Museu_Label;
    private javax.swing.JLabel Pagador_Label;
    private javax.swing.JLabel Preco_Label;
    private javax.swing.JLabel Tipo_Transporte_Label;
    private javax.swing.JLabel Tipo_de_Operacao;
    private javax.swing.JLabel Titulo_Label;
    private javax.swing.JLabel Transporte_Label;
    private javax.swing.JButton Voltar_botao;
    private javax.swing.JComboBox cbMuseuEmp;
    private javax.swing.JComboBox cbPagadorTransporteEmp;
    private javax.swing.JComboBox cbTipoOperacaoEmp;
    private javax.swing.JComboBox cbTipoTransporteEmpr;
    private javax.swing.JFormattedTextField ftfDataOperacaoEmp;
    private javax.swing.JTextField tfAutorEmp;
    private javax.swing.JTextField tfCodigoEmp;
    private javax.swing.JTextField tfEmpresaTranspEmp;
    private javax.swing.JTextField tfPrecoTransporteEmp;
    private javax.swing.JTextField tfTituloEmp;
    // End of variables declaration//GEN-END:variables
}
