/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import control.ExposicaoControl;
import entity.ExposicaoBean;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows
 */
public class ManterExposicao extends javax.swing.JFrame {

    DefaultTableModel tmExposicao = new DefaultTableModel(null, new String[]{"Exposicao", "Data Inicio", "Data Fim"});
    ListSelectionModel lsmExposicao;
    List<ExposicaoBean> exposicoes;
            
    public ManterExposicao() {
        System.out.println("Iniciando initComponents()");                
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pesqB1 = new javax.swing.JButton();
        lbCodExposicao = new javax.swing.JLabel();
        lbNomeExposicao = new javax.swing.JLabel();
        lbDescricaoExposicao = new javax.swing.JLabel();
        lbDataInicioExposicao = new javax.swing.JLabel();
        lbDataTerminoExposicao = new javax.swing.JLabel();
        lbPisoExposicao = new javax.swing.JLabel();
        lbSetorExposicao = new javax.swing.JLabel();
        tfCodExposicao = new javax.swing.JTextField();
        tfNomeExposicao = new javax.swing.JTextField();
        tfDescricaoExposicao = new javax.swing.JTextField();
        btGravarExposicao = new javax.swing.JButton();
        btExcluirExposicao = new javax.swing.JButton();
        cbPiso = new javax.swing.JComboBox();
        cbSetor = new javax.swing.JComboBox();
        btLimpar = new javax.swing.JButton();
        ftfDataInicioExposicao = new javax.swing.JFormattedTextField();
        ftfDataFimExposicao = new javax.swing.JFormattedTextField();
        btAlterarExposicao = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbExposicao = new javax.swing.JTable();
        btnPesquisaNome = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        pesqB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/imgLupa.jpg"))); // NOI18N

        setResizable(false);

        lbCodExposicao.setText("Cód. da Exposição:");
        lbCodExposicao.setName("lbCodExposicao"); // NOI18N

        lbNomeExposicao.setText("Nome da Exposição:");
        lbNomeExposicao.setName("lbNomeExposicao"); // NOI18N

        lbDescricaoExposicao.setText("Descrição da Exposição:");
        lbDescricaoExposicao.setName("lblDescricaoDaExposicao"); // NOI18N

        lbDataInicioExposicao.setText("Data de Início:");
        lbDataInicioExposicao.setName("lblDataInicio"); // NOI18N

        lbDataTerminoExposicao.setText("Data de Término:");
        lbDataTerminoExposicao.setName("lblDataFim"); // NOI18N

        lbPisoExposicao.setText("Piso:");
        lbPisoExposicao.setName("lblPiso"); // NOI18N

        lbSetorExposicao.setText("Setor:");
        lbSetorExposicao.setToolTipText("");
        lbSetorExposicao.setName("lblSetor"); // NOI18N

        tfCodExposicao.setEditable(false);
        tfCodExposicao.setName("tfCodExposicao"); // NOI18N

        tfNomeExposicao.setName("tfNomeExposicao"); // NOI18N

        tfDescricaoExposicao.setName("tfDescricaoExposicao"); // NOI18N

        btGravarExposicao.setText("Gravar");
        btGravarExposicao.setName("btGravarExposicao"); // NOI18N
        btGravarExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarExposicaoActionPerformed(evt);
            }
        });

        btExcluirExposicao.setText("Excluir");
        btExcluirExposicao.setToolTipText("");
        btExcluirExposicao.setEnabled(false);
        btExcluirExposicao.setName("btExcluirExposicao"); // NOI18N

        cbPiso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Norte", "Sul", "Leste", "Oeste" }));

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        try {
            ftfDataInicioExposicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfDataFimExposicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btAlterarExposicao.setText("Alterar");
        btAlterarExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarExposicaoActionPerformed(evt);
            }
        });

        tbExposicao.setModel(tmExposicao);
        tbExposicao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmExposicao = tbExposicao.getSelectionModel();
        lsmExposicao.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    tbExposicaoLinhaSelecionada(tbExposicao);
                }
            }
        });
        jScrollPane3.setViewportView(tbExposicao);

        btnPesquisaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boundary/imgLupa.jpg"))); // NOI18N
        btnPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCodExposicao)
                        .addGap(27, 27, 27)
                        .addComponent(tfCodExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeExposicao)
                        .addGap(23, 23, 23)
                        .addComponent(tfNomeExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDescricaoExposicao)
                        .addGap(4, 4, 4)
                        .addComponent(tfDescricaoExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDataInicioExposicao)
                        .addGap(50, 50, 50)
                        .addComponent(ftfDataInicioExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbPisoExposicao)
                        .addGap(17, 17, 17)
                        .addComponent(cbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDataTerminoExposicao)
                        .addGap(37, 37, 37)
                        .addComponent(ftfDataFimExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbSetorExposicao)
                        .addGap(10, 10, 10)
                        .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluirExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btAlterarExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btGravarExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbCodExposicao))
                    .addComponent(tfCodExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbNomeExposicao))
                    .addComponent(tfNomeExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbDescricaoExposicao))
                    .addComponent(tfDescricaoExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataInicioExposicao)
                    .addComponent(ftfDataInicioExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPisoExposicao)
                    .addComponent(cbPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDataTerminoExposicao)
                    .addComponent(ftfDataFimExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSetorExposicao)
                    .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btLimpar)
                    .addComponent(btExcluirExposicao)
                    .addComponent(btAlterarExposicao)
                    .addComponent(btGravarExposicao))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lbNomeExposicao.getAccessibleContext().setAccessibleName("");
        lbNomeExposicao.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tbExposicaoLinhaSelecionada(JTable tb){
          
        if (tb.getSelectedRow() != -1){
            tfCodExposicao.setText(exposicoes.get(tb.getSelectedRow()).getCodigoExposicao().toString());
            tfNomeExposicao.setText(exposicoes.get(tb.getSelectedRow()).getNomeExposicao());
            tfDescricaoExposicao.setText(exposicoes.get(tb.getSelectedRow()).getDescricaoExposicao());
            cbPiso.setSelectedItem(exposicoes.get(tb.getSelectedRow()).getPiso());
            cbSetor.setSelectedItem(exposicoes.get(tb.getSelectedRow()).getSetor());
            ftfDataInicioExposicao.setText(exposicoes.get(tb.getSelectedRow()).getDataInicioExposicao());
            ftfDataFimExposicao.setText(exposicoes.get(tb.getSelectedRow()).getDataFimExposicao());
        }
    }
   
    
    private void btGravarExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarExposicaoActionPerformed
        cadastraExposicao();
    }//GEN-LAST:event_btGravarExposicaoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpaTela();
    }//GEN-LAST:event_btLimparActionPerformed

       
    public void mostrarExposicao(List<ExposicaoBean> exposicao){
        while(tmExposicao.getRowCount() > 0){
            tmExposicao.removeRow(0);
        }
        if(exposicao.size() > 0){
            String [] campos = new String[] {null, null, null, null};
            for(int i = 0; i < exposicao.size(); i++){
                tmExposicao.addRow(campos);
                tmExposicao.setValueAt(exposicao.get(i).getNomeExposicao(), i, 0);
                tmExposicao.setValueAt(exposicao.get(i).getDataInicioExposicao(), i, 1);
                tmExposicao.setValueAt(exposicao.get(i).getDataFimExposicao(), i, 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma obra encontrada!", "Control + Art", 2);
        }
    }
    public void mostrarExposicaoNome(){
        ExposicaoControl exp = new ExposicaoControl();
        exposicoes = exp.mostrarExposicaoNome(tfNomeExposicao.getText().trim());
        mostrarExposicao(exposicoes);
    }
    
    private void btnPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeActionPerformed
        mostrarExposicaoNome();
    }//GEN-LAST:event_btnPesquisaNomeActionPerformed

    public void alteraExposicao(){
        
        ExposicaoBean exposicao = new ExposicaoBean();
        exposicao.setCodigoExposicao(Integer.parseInt(tfCodExposicao.getText().trim()));
        exposicao.setNomeExposicao(tfNomeExposicao.getText().trim());
        exposicao.setDescricaoExposicao(tfDescricaoExposicao.getText().trim());
        exposicao.setDataInicioExposicao(ftfDataInicioExposicao.getText());
        exposicao.setDataFimExposicao(ftfDataFimExposicao.getText());
        exposicao.setPiso(Integer.parseInt(cbPiso.getSelectedItem().toString()));
        exposicao.setSetor(cbSetor.getSelectedItem().toString());
        ExposicaoControl c = new ExposicaoControl();
        c.alterarExposicao(exposicao);
        JOptionPane.showMessageDialog(null, "Exposicçao cadastrada com sucesso", "Control + Art", 3);
    }
    
    private void btAlterarExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarExposicaoActionPerformed
        alteraExposicao();
    }//GEN-LAST:event_btAlterarExposicaoActionPerformed

    public void cadastraExposicao(){
        
        ExposicaoBean exposicao = new ExposicaoBean();
        exposicao.setNomeExposicao(tfNomeExposicao.getText().trim());
        exposicao.setDescricaoExposicao(tfDescricaoExposicao.getText().trim());
        exposicao.setDataInicioExposicao(ftfDataInicioExposicao.getText());
        exposicao.setDataFimExposicao(ftfDataFimExposicao.getText());
        exposicao.setPiso(Integer.parseInt(cbPiso.getSelectedItem().toString()));
        exposicao.setSetor(cbSetor.getSelectedItem().toString());
        ExposicaoControl c = new ExposicaoControl();
        c.cadastrarExposicao(exposicao);
        JOptionPane.showMessageDialog(null, "Exposicçao cadastrada com sucesso", "Control + Art", 3);
        limpaTela();
        
        
        
    }
    
    private void limpaTela(){
        while(tmExposicao.getRowCount() > 0){
            tmExposicao.removeRow(0);
        }
        tfCodExposicao.setText("");
        tfNomeExposicao.setText("");
        tfDescricaoExposicao.setText("");
        ftfDataInicioExposicao.setText("");
        ftfDataFimExposicao.setText("");
        cbPiso.setSelectedItem(0);
        cbSetor.setSelectedItem(0);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterExposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterExposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterExposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterExposicao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterExposicao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarExposicao;
    private javax.swing.JButton btExcluirExposicao;
    private javax.swing.JButton btGravarExposicao;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btnPesquisaNome;
    private javax.swing.JComboBox cbPiso;
    private javax.swing.JComboBox cbSetor;
    private javax.swing.JFormattedTextField ftfDataFimExposicao;
    private javax.swing.JFormattedTextField ftfDataInicioExposicao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbCodExposicao;
    private javax.swing.JLabel lbDataInicioExposicao;
    private javax.swing.JLabel lbDataTerminoExposicao;
    private javax.swing.JLabel lbDescricaoExposicao;
    private javax.swing.JLabel lbNomeExposicao;
    private javax.swing.JLabel lbPisoExposicao;
    private javax.swing.JLabel lbSetorExposicao;
    private javax.swing.JButton pesqB1;
    private javax.swing.JTable tbExposicao;
    private javax.swing.JTextField tfCodExposicao;
    private javax.swing.JTextField tfDescricaoExposicao;
    private javax.swing.JTextField tfNomeExposicao;
    // End of variables declaration//GEN-END:variables
}
