/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

/**
 *
 * @author cluster
 */
public class TelaVisitante extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisitante
     */
    public TelaVisitante() {
        initComponents();
        
        tbtnCompleto.setVisible(false);
        tbtnIncompleto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSexo = new javax.swing.ButtonGroup();
        btnGroupIdade = new javax.swing.ButtonGroup();
        btnGroupEscolaridade = new javax.swing.ButtonGroup();
        btnGroupOrigem = new javax.swing.ButtonGroup();
        btnGroupCompleto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbtnMasc = new javax.swing.JToggleButton();
        tbtnFem = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        tbtnKids = new javax.swing.JToggleButton();
        tbtnYoung = new javax.swing.JToggleButton();
        tbtnAdult = new javax.swing.JToggleButton();
        tbtnAged = new javax.swing.JToggleButton();
        btnNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tbtnBasico = new javax.swing.JToggleButton();
        tbtnSuperior = new javax.swing.JToggleButton();
        tbtnPosGradu = new javax.swing.JToggleButton();
        tbtnCompleto = new javax.swing.JToggleButton();
        tbtnIncompleto = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Recebe Visitante"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("NOME / NAME:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("SEXO / GENDER: ");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel7.setText("IDADE / AGE: ");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("De onde você vem? / Where are you from?");

        btnGroupSexo.add(tbtnMasc);
        tbtnMasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/user_man_small.png"))); // NOI18N

        btnGroupSexo.add(tbtnFem);
        tbtnFem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/user_woman_small.png"))); // NOI18N

        btnGroupOrigem.add(jToggleButton3);
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/brasil.png"))); // NOI18N

        btnGroupOrigem.add(jToggleButton4);
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/earth.png"))); // NOI18N

        btnGroupIdade.add(tbtnKids);
        tbtnKids.setText(" <14 anos/years");
        tbtnKids.setPreferredSize(new java.awt.Dimension(135, 29));

        btnGroupIdade.add(tbtnYoung);
        tbtnYoung.setText("15 - 20 anos/years");

        btnGroupIdade.add(tbtnAdult);
        tbtnAdult.setText("21 - 60 anos/years");

        btnGroupIdade.add(tbtnAged);
        tbtnAged.setText("> 60 anos/years");
        tbtnAged.setPreferredSize(new java.awt.Dimension(135, 29));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/forward_small.png"))); // NOI18N
        btnNext.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/forward_small.png"))); // NOI18N

        btnGroupEscolaridade.add(tbtnBasico);
        tbtnBasico.setText("Básico / Basic");
        tbtnBasico.setMaximumSize(new java.awt.Dimension(219, 29));
        tbtnBasico.setMinimumSize(new java.awt.Dimension(219, 29));
        tbtnBasico.setPreferredSize(new java.awt.Dimension(150, 35));
        tbtnBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnBasicoActionPerformed(evt);
            }
        });

        btnGroupEscolaridade.add(tbtnSuperior);
        tbtnSuperior.setText("Superior/ Higher");
        tbtnSuperior.setMaximumSize(new java.awt.Dimension(219, 29));
        tbtnSuperior.setMinimumSize(new java.awt.Dimension(219, 29));
        tbtnSuperior.setPreferredSize(new java.awt.Dimension(150, 35));
        tbtnSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSuperiorActionPerformed(evt);
            }
        });

        btnGroupEscolaridade.add(tbtnPosGradu);
        tbtnPosGradu.setText("Pós-Graduação/Postgraduate");
        tbtnPosGradu.setPreferredSize(new java.awt.Dimension(150, 35));
        tbtnPosGradu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPosGraduActionPerformed(evt);
            }
        });

        btnGroupCompleto.add(tbtnCompleto);
        tbtnCompleto.setText("Completo / Complete");
        tbtnCompleto.setMaximumSize(new java.awt.Dimension(219, 29));
        tbtnCompleto.setMinimumSize(new java.awt.Dimension(219, 29));
        tbtnCompleto.setPreferredSize(new java.awt.Dimension(150, 35));
        tbtnCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnCompletoActionPerformed(evt);
            }
        });

        btnGroupCompleto.add(tbtnIncompleto);
        tbtnIncompleto.setText("Incompleto / Incomplete");
        tbtnIncompleto.setMaximumSize(new java.awt.Dimension(219, 29));
        tbtnIncompleto.setMinimumSize(new java.awt.Dimension(219, 29));
        tbtnIncompleto.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel9.setText("ESCOLARIDADE \n/ EDUCATION: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbtnBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnPosGradu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(tbtnCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbtnIncompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnPosGradu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnIncompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(343, 343, 343)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButton4))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNext))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(78, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbtnKids, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbtnYoung, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbtnAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tbtnAged, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tbtnMasc)
                                        .addGap(45, 45, 45)
                                        .addComponent(tbtnFem))
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnFem)
                            .addComponent(tbtnMasc))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tbtnKids, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnYoung, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnAged, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton3)
                            .addComponent(jToggleButton4))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNext)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tbtnCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbtnCompletoActionPerformed

    private void tbtnSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSuperiorActionPerformed
        tbtnCompleto.setVisible(true);
        tbtnIncompleto.setVisible(true);
    }//GEN-LAST:event_tbtnSuperiorActionPerformed

    private void tbtnPosGraduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPosGraduActionPerformed
        tbtnCompleto.setVisible(true);
        tbtnIncompleto.setVisible(true);
    }//GEN-LAST:event_tbtnPosGraduActionPerformed

    private void tbtnBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnBasicoActionPerformed
        tbtnCompleto.setVisible(true);
        tbtnIncompleto.setVisible(true);
    }//GEN-LAST:event_tbtnBasicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCompleto;
    private javax.swing.ButtonGroup btnGroupEscolaridade;
    private javax.swing.ButtonGroup btnGroupIdade;
    private javax.swing.ButtonGroup btnGroupOrigem;
    private javax.swing.ButtonGroup btnGroupSexo;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton tbtnAdult;
    private javax.swing.JToggleButton tbtnAged;
    private javax.swing.JToggleButton tbtnBasico;
    private javax.swing.JToggleButton tbtnCompleto;
    private javax.swing.JToggleButton tbtnFem;
    private javax.swing.JToggleButton tbtnIncompleto;
    private javax.swing.JToggleButton tbtnKids;
    private javax.swing.JToggleButton tbtnMasc;
    private javax.swing.JToggleButton tbtnPosGradu;
    private javax.swing.JToggleButton tbtnSuperior;
    private javax.swing.JToggleButton tbtnYoung;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
