/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package boundary;

import boundary.ManterObra;
import javax.swing.JOptionPane;

/**
 *
 * @author teste
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExposicao = new javax.swing.JButton();
        btnObras = new javax.swing.JButton();
        btnEmprestimo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        sairMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        autorMenu = new javax.swing.JMenuItem();
        mnuExposicao = new javax.swing.JMenuItem();
        mnuObras = new javax.swing.JMenuItem();
        mnuRegistrarEmprestimo = new javax.swing.JMenu();
        emprestMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        visitanteMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExposicao.setText("Exposição");
        btnExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExposicaoActionPerformed(evt);
            }
        });

        btnObras.setText("Obras");
        btnObras.setToolTipText("Obras");
        btnObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrasActionPerformed(evt);
            }
        });

        btnEmprestimo.setText("Operações de Emprestimo");
        btnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprestimoActionPerformed(evt);
            }
        });

        jButton4.setText("Receber Visitante");
        jButton4.setToolTipText("");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        sairMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        sairMenu.setText("Sair");
        sairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuActionPerformed(evt);
            }
        });
        fileMenu.add(sairMenu);

        jMenuBar1.add(fileMenu);

        jMenu2.setText("Cadastrar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        autorMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        autorMenu.setText("Autor");
        jMenu2.add(autorMenu);

        mnuExposicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuExposicao.setText("Exposição");
        mnuExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExposicaoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExposicao);

        mnuObras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuObras.setText("Obras");
        mnuObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuObrasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuObras);

        jMenuBar1.add(jMenu2);

        mnuRegistrarEmprestimo.setText("Emprestimos");

        emprestMenu.setText("Registrar Emprestimo");
        emprestMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestMenuActionPerformed(evt);
            }
        });
        mnuRegistrarEmprestimo.add(emprestMenu);

        jMenuBar1.add(mnuRegistrarEmprestimo);

        jMenu1.setText("Visitantes");

        visitanteMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        visitanteMenu.setText("Receber Visitante");
        visitanteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitanteMenuActionPerformed(evt);
            }
        });
        jMenu1.add(visitanteMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnObras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmprestimo, btnExposicao, btnObras});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObras, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExposicaoActionPerformed
        // TODO add your handling code here:
        new ManterExposicao().setVisible(true);
    }//GEN-LAST:event_btnExposicaoActionPerformed

    private void sairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuActionPerformed
        if(0 == JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente sair?","Sair",0,JOptionPane.PLAIN_MESSAGE))
            System.exit(0);
    }//GEN-LAST:event_sairMenuActionPerformed

    private void mnuObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuObrasActionPerformed
        new ManterObra().setVisible(true);
    }//GEN-LAST:event_mnuObrasActionPerformed

    private void mnuExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExposicaoActionPerformed
        //new ManterExposicao().setVisible(true);
    }//GEN-LAST:event_mnuExposicaoActionPerformed

    private void emprestMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestMenuActionPerformed
        // TODO add your handling code here:
        new ManterEmprestimo().setVisible(true);
    }//GEN-LAST:event_emprestMenuActionPerformed

    private void visitanteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitanteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitanteMenuActionPerformed

    private void btnObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrasActionPerformed
        new ManterObra().setVisible(true);
    }//GEN-LAST:event_btnObrasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        new ManterExposicao().setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void btnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestimoActionPerformed
        // TODO add your handling code here:
        new ManterEmprestimo().setVisible(true);
    }//GEN-LAST:event_btnEmprestimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem autorMenu;
    private javax.swing.JButton btnEmprestimo;
    private javax.swing.JButton btnExposicao;
    private javax.swing.JButton btnObras;
    private javax.swing.JMenuItem emprestMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuExposicao;
    private javax.swing.JMenuItem mnuObras;
    private javax.swing.JMenu mnuRegistrarEmprestimo;
    private javax.swing.JMenuItem sairMenu;
    private javax.swing.JMenuItem visitanteMenu;
    // End of variables declaration//GEN-END:variables
}
