/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import javax.swing.JOptionPane;

/**
 *
 * @author cluster
 */
public class Transporte extends javax.swing.JFrame {

    /**
     * Creates new form Transporte
     */
    public Transporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        btnGroupTransporte = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbtnAndar = new javax.swing.JToggleButton();
        tbtnMetro = new javax.swing.JToggleButton();
        tbtnCarro = new javax.swing.JToggleButton();
        tbtnTaxi = new javax.swing.JToggleButton();
        tbtnOnibus = new javax.swing.JToggleButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Como você chegou até o MASP hoje?");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setText("How did you get the MASP today?");

        btnGroupTransporte.add(tbtnAndar);
        tbtnAndar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/walking_small.png"))); // NOI18N

        btnGroupTransporte.add(tbtnMetro);
        tbtnMetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/metro_small.png"))); // NOI18N

        btnGroupTransporte.add(tbtnCarro);
        tbtnCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/car.png"))); // NOI18N

        btnGroupTransporte.add(tbtnTaxi);
        tbtnTaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/taxi_small.png"))); // NOI18N

        btnGroupTransporte.add(tbtnOnibus);
        tbtnOnibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/bus_small.png"))); // NOI18N

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/forward_small.png"))); // NOI18N
        btnNext.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imageRepository/forward_small.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(tbtnOnibus)
                        .addGap(105, 105, 105)
                        .addComponent(tbtnMetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tbtnAndar)
                                .addGap(99, 99, 99)
                                .addComponent(tbtnCarro)
                                .addGap(106, 106, 106)
                                .addComponent(tbtnTaxi)))
                        .addGap(12, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(177, 177, 177))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtnAndar)
                    .addComponent(tbtnCarro)
                    .addComponent(tbtnTaxi))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtnOnibus)
                            .addComponent(tbtnMetro))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (verificaSelecao()){
            new TelaVisitante().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Você deve selecionar um meio de transporte.\n"
                    + "You must select a mode of transport.","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private boolean verificaSelecao(){
        return (tbtnAndar.isSelected()||tbtnCarro.isSelected()||
                tbtnMetro.isSelected() || tbtnOnibus.isSelected() ||
                tbtnTaxi.isSelected());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupTransporte;
    private javax.swing.JButton btnNext;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton tbtnAndar;
    private javax.swing.JToggleButton tbtnCarro;
    private javax.swing.JToggleButton tbtnMetro;
    private javax.swing.JToggleButton tbtnOnibus;
    private javax.swing.JToggleButton tbtnTaxi;
    // End of variables declaration//GEN-END:variables
}
